### ISSUE TITLE
Numerical Query Parameter Parsing not working as intended

### ISSUE THREAD

**Issue by ciaranduncan14596** [jayalfredprufrock/nestjs-typebox#61] opened 2024-10-25 18:13 UTC
Hey 

Currently encountering an issue with validating non-numerical query parameter types. I have a cURL request as so
```
curl --request GET 'http://localhost:3000/path/123?cursor=1' 
```
And the validation schema looks something like this
```
  @Validate({
    request: [
      { type: 'param', name: 'id', schema: Type.Number(), coerceTypes: true },
      { type: 'query', name: 'cursor', schema: Type.Optional(Type.Number()), coerceTypes: true },
      { type: 'query', name: 'pageSize', schema: Type.Optional(Type.Number()), coerceTypes: true },
      { type: 'query', name: 'productId', schema: Type.Optional(Type.Number()), coerceTypes: true },
    ],
  })
  getRequest(id: number, cursor = 0, pageSize = 20, productId?: number): Promise<GetPaginatedResponse> {
```
In doing so I'm presented with an error message as so 
```
{
	"statusCode": 400,
	"message": "Validation failed (query)",
	"errors": [
		{
			"type": 41,
			"schema": {
				"type": "number"
			},
			"path": "",
			"value": "1",
			"message": "Expected number",
			"errors": []
		}
	]
}
```
After debugging the checker.Check function [here](https://github.com/jayalfredprufrock/nestjs-typebox/blob/7e9c52a2aa1d5fce5db2424b2e1529f2e6051def/src/decorators.ts#L74) it looks like the query parameter itself isn't typed into a number before getting into this `buildSchemaValidator` 

The same issue isnt the case with the `id` param here as `123` is parsed correctly. 

Is there a known limitation with parsing query parameters? Am I missing something?

**Comment by jayalfredprufrock** [comment] 2024-10-25 18:24
Thanks for submitting an issue! At first glance, this looks to be an issue specifically with optional parameters. I'm going to need to consult the typebox docs around the check function behavior and optional parameters to see what about this validation pipeline I'm getting wrong (I modeled this code directly after the official parse function: https://github.com/sinclairzx81/typebox/blob/master/src/value/parse/parse.ts). It could be that this is a bug in typebox itself, in which case the maintainer is incredibly active and will most certainly push a timely fix. Otherwise, I might need to make a special case around the offending line and unwrap the optional specifier before attempting the coercion step.

One way or another this definitely needs to be addressed ASAP. I rarely use optional path parameters, but I'm concerned that this could be affecting optional query parameters as well, in which case I have production code that could be affected.

**Comment by ciaranduncan14596** [comment] 2024-10-25 18:35
Hey @jayalfredprufrock thanks for the quick response

To confirm I *don't* believe this is limited to just the optional parameters e.g by dropping the optional here 
```
 { type: 'query', name: 'cursor', schema: Type.Number(), coerceTypes: true },
```
I still hit the same issue.

and just to quote you here 

> but I'm concerned that this could be affecting optional query parameters as well, in which case I have production code that could be affected.

I am definitely seeing it affecting optional query parameters here (as the cursor param is an optional) - The above validation is OK on the path param but not with the optional query param

**Comment by jayalfredprufrock** [comment] 2024-10-25 18:38
Thanks for clarifying, I think I see what's going on now. I should be able to put together a fix today and post back.

**Comment by ciaranduncan14596** [comment] 2024-10-25 18:58
Amazing - thank you so much!

**Comment by jayalfredprufrock** [comment] 2024-10-25 20:25
Just pushed a release that should fix this issue. I'll leave this open until you've had a chance to verify on your end. Thanks again for bringing this to my attention!

**Comment by ciaranduncan14596** [comment] 2024-10-25 21:44
Hey @jayalfredprufrock - appreciate the effort on this. I've attempted to verify this and noticed a small issue - I'll attempt to demonstrate using my example above 
```
 @Validate({
    request: [
      { type: 'param', name: 'id', schema: Type.Number(), coerceTypes: true },
      { type: 'query', name: 'cursor', schema: Type.Optional(Type.Number()), coerceTypes: true },
      { type: 'query', name: 'pageSize', schema: Type.Optional(Type.Number()), coerceTypes: true },
      { type: 'query', name: 'productId', schema: Type.Optional(Type.Number()), coerceTypes: true },
    ],
  })
  getRequest(id: number, cursor = 0, pageSize = 20, productId?: number): Promise<GetPaginatedResponse> {
```

The first two query parameters now work fine - leaving them blank via a curl request e.g 
```
curl --request GET 'http://localhost:3000/path/123?productId=1' 
```
now works fine - this is because they default to either 0 or 20 in the case above. The issue arises now with productId. I believe because its type is simply `number` the validator cannot compute a value and assigns it to `NaN` and the following error message e.g 

```
{
	"statusCode": 400,
	"message": "Validation failed (query)",
	"errors": [
		{
			"type": 41,
			"schema": {
				"type": "number"
			},
			"path": "",
			"value": null,
			"message": "Expected number",
			"errors": []
		}
	]
}
```
I've added a debugger screenshot to illustrate - hope this helps  
![Screenshot 2024-10-25 at 22 42 46](https://github.com/user-attachments/assets/5f6af9cc-7e73-4daa-bd0a-9487eb0bcc94)

**Comment by jayalfredprufrock** [comment] 2024-10-25 21:56
@ciaranduncan14596 bummer, I'm not able to reproduce using your example. Could you post what version of typebox you are using? I'm on the latest 0.33.17. I know there has been some movement and bug fixes surrounding the value system so I want to rule a version mismatch out before I dig any deeper.

**Comment by ciaranduncan14596** [comment] 2024-10-25 22:17
Hey @jayalfredprufrock - yes. 
`"@sinclair/typebox": "^0.33.17",`

But looks like one of our dependencies (namely jest appears to be using `"@sinclair/typebox": "^0.27.8"` ) so node_modules is likely using that

**Comment by jayalfredprufrock** [comment] 2024-10-25 22:41
So I think at this point we'll need a minimal reproduction. I'll get a codesandbox going with a minimal example that we can use to try and reproduce, but I likely won't get to that today. If you are able to put together something you can share in the meantime that would be awesome, but in general I don't feel comfortable asking the community to do that while I don't have proper unit test coverage :)

**Comment by ciaranduncan14596** [comment] 2024-10-25 23:20
Hey @jayalfredprufrock ill likely not get a sandbox put together myself this weekend but should be able to help reproduce/debug regardless

As an aside - Not being an expert in the code base from a quick look I think we could fix this issue with something like (Please disregard if this is nonsensical) 

By placing this at the start of the `validate` function in `buildSchemaValidator`
```
 if (Number.isNaN(data)) {
    if (!Object.getOwnPropertySymbols(schema).map(sym => schema[sym]).includes('Optional')) {
      throw new exceptions_js_1.TypeboxValidationException(type, [{
        message: 'Did not receive required param'
    }]);
  } else {
    return
  }
```

Essentially check if the Query Parameter is a NaN (i.e its not been provided) we check if the property is Optional (by extracting the symbols from the typebox schema that allow us to determine this and checking for the optional string)

If the property is optional we can return and go no further - otherwise proceed through the rest of the validation checks

In my case above it works but not sure of the effects elsewhere (more a food for thought?)

**Comment by jayalfredprufrock** [comment] 2024-10-26 00:40
Here is a starting off point: https://codesandbox.io/p/devbox/4qfqjq

When you get a chance, see if you can add code back until you recreate the issue. Fingers crossed we can get to the bottom of this.

Cheers!

**Comment by ahstn** [comment] 2024-10-26 12:24
Hey @jayalfredprufrock , figured out how to replicate it: https://codesandbox.io/p/devbox/4qfqjq

Only change I made from yours is enabling:
```diff
async function bootstrap() {
    const app = await NestFactory.create(AppModule);
+   app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true }));
    await app.listen(3000);
}
```

Best guess is that NestJS' transformer ([Global Scoped Pipes | NestJS](https://docs.nestjs.com/pipes#global-scoped-pipes)) is clashing with `nestjs-typebox`, but I don't think having global transformers makes sense here either? 

I'm not sure what can be done to accommodate both, but Maybe it's just something to call out in the `README.md` rather than a code change 🤔

**Comment by jayalfredprufrock** [comment] 2024-10-26 14:29
Ahh yes, the nestjs-typebox decorator is meant to replace the validation pipe and all of the DTO related packages/patterns. I can definitely make that more clear in the docs. Thank you @ahstn for looking into this! 

@ciaranduncan14596 does this explain the behavior you are seeing?

**Comment by ciaranduncan14596** [comment] 2024-10-26 21:46
Hey @jayalfredprufrock yes!!! 

Removing the `useGlobalPipes` set up in my `main.ts` and this now works as expected

Agree with @ahstn that a small update to the `README.md` would clear all this up - excellent spot @ahstn

**Comment by jayalfredprufrock** [comment] 2024-10-26 21:57
Wonderful, really appreciate the help here. I'm going to close this issue out, but please do keep an eye out for any other issues. I've got a big project releasing early next year using this lib so I'm keen on teasing out any remaining issues with v3. 

Cheers, Andrew

**Closed by jayalfredprufrock** 2024-10-26 21:57 UTC
